//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingEFInAzureSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int ContactID { get; set; }
        public int CustomerTypeID { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<int> PrimaryDesintation { get; set; }
        public Nullable<int> SecondaryDestination { get; set; }
        public Nullable<int> PrimaryActivity { get; set; }
        public Nullable<int> SecondaryActivity { get; set; }
        public string Notes { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Activity Activity1 { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
