//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingEFInAzureSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldReservation
    {
        public int ReservationID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> EventID { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
